### ISSUE TITLE
simulation.run can't handle whitespace in arguments

### ISSUE THREAD

**Issue by sjalloq** [themperek/cocotb-test#137] opened 2021-03-11 11:03 UTC
Not sure if this is by design or not, but it took me a while to track down why `vsim` was not accepting my `sim_args`.  It looks like you escape white space but don't remove the escape parameters before invoking `vsim`.

`sim_args=[ "-l logfile.log" ]` results in `vsim -l\ logfile.log`.

To fix this I seem to need to specify each argument individually: `sim_args=[ "-l", "logfile.log" ]`

**Comment by themperek** [comment] 2021-03-12 17:41
Would need `.split()` all commands string that goes here :
https://github.com/themperek/cocotb-test/blob/f31e43d5c15392dc976a01eccb7bc5ed6a72c790/cocotb_test/simulator.py#L252-L253

**Comment by sjalloq** [comment] 2021-03-12 20:17
Sorry, not sure what you're saying.  Are you suggesting a workaround or stating a reason why it's done that way?

**Comment by themperek** [comment] 2021-03-12 20:19
One way to solve this problem.

**Comment by alexforencich** [comment] 2023-01-18 22:28
I think this is just how arguments are passed to processes.  If you want two arguments, you use two items in the list.  This removes the ambiguity of spaces in file names and what not - if it's one entry in the list, it's one argument, even if it contains spaces.  So, IMO this is cocotb-test working exactly as it should.

**Comment by themperek** [comment] 2023-01-19 08:47
@alexforencich is right. It is a feutre not a bug. I will close this in case please feel free to reopen.

**Closed by themperek** 2023-01-19 08:47 UTC
